randomizer/generator/urls.py
from django.urls import path
from generator.views import *

app_name = 'generator'
urlpatterns = [
    path('', index, name='index'),
    path('raffles/<slug:slug>/', raffle_page, name='raffle_page'),
    path('my_raffles/', my_raffles, name='my_raffles'),
    path('new_raffle/', VkForm.as_view(), name='new_raffle'),
    path('thankyou/', thankyou, name='thankyou'),

]

randomizer/randomizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('generator.urls')),
    path('lk/', include('user_cabinet.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

randomizer/user_cabinet/urls.py
from django.urls import path
from user_cabinet.views import *

app_name = 'user_cabinet'
urlpatterns = [
    path('', index_lk, name='index_lk'),
    path('display_name_update/', DisplayNameUpdate.as_view(), name='display_name_update'),
    path('display_name_update_ok', display_name_update_ok, name='display_name_update_ok'),
    path('api_key_update', api_key_update, name='api_key_update'),
    path('api_key_update_ok', api_key_update_ok, name='api_key_update_ok'),
]

randomizer/users/urls.py
from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                    )
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('access_denied/', access_denied, name='access_denied'),
    path('auth_vk_key/', auth_vk_key, name='auth_vk_key'),
    path('auth_vk_complete/', auth_vk_complete, name='auth_vk_complete'),
        
]

randomizer/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'generator:index' %}"><img src="{% static 'img/logo2.jpeg' %}"
        class="img-fluid" width='350px' alt="Рандомайзер-2000"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% block navbar %}
        {% if request.user.is_authenticated %}
        {% if user.get_username == 'twsomt' %}
        <li class="nav-item">
          <a class="nav-link" href="/admin/">@admin</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'generator:new_raffle' %}">Новый конкурс</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_cabinet:index_lk' %}">Личный кабинет</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
            {% if user.client.display_name %}
              {{ user.client.display_name }}
            {% elif user.first_name and user.last_name %}
              {{ user.get_full_name }}
            {% else %}
              {{ user.get_username }}
            {% endif %}
          </a>
        </li>
        {% endif %}
        {% if not request.user.is_authenticated %}
        <li class="text-secondary" style="">
          Ваш помощник в проведении конкурсов
        </li>
        {% endif %}
        {% endblock %}
      </ul>
    </div>
  </div>
</nav>