randomizer/generator/urls.py
from django.urls import path
from generator.views import *

app_name = 'generator'
urlpatterns = [
    path('', index, name='index'),
    path('raffles/<slug:slug>/', raffle_page, name='raffle_page'),
    path('my_raffles/', my_raffles, name='my_raffles'),
    path('new_raffle/', VkForm.as_view(), name='new_raffle'),
    path('thankyou/', thankyou, name='thankyou'),

]

randomizer/randomizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('generator.urls')),
    path('lk/', include('user_cabinet.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

randomizer/users/urls.py
from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                    )
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('access_denied/', access_denied, name='access_denied'),
    path('auth_vk_key/', auth_vk_key, name='auth_vk_key'),
    path('auth_vk_complete/', auth_vk_complete, name='auth_vk_complete'),
        
]

randomizer/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()
from captcha.fields import CaptchaField


class CreationForm(UserCreationForm):
    captcha = CaptchaField(label='Cимволы с картинки:')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'username', 'email')

randomizer/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm
from django.shortcuts import render, redirect
from generator.models import Client
from datetime import datetime as dt

def secret_enter(func):
    def check_user(request, *args, **kwargs):
        password = self.request.GET.get('pswrd', '')
        if password == 'lkjr6tyyr416vvv35445dtyb':
            return func(request, *args, **kwargs)
        return redirect('access_denied/')
    return check_user

# @secret_enter
class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('generator:index')
    template_name = 'users/signup.html'

def access_denied(request):
    return render(request, 'users/access_denied.html')


def auth_vk_complete(request):
    error = request.GET.get('error', '')
    error_description = request.GET.get('error_description', '')
    context = {
        'error': error,
        'error_description': error_description,
    }
    
    access_token = request.GET.get('token', '123')

    if not error:
        try:
            usr = Client.objects.get(user=request.user)
        except:
            usr = False
            
        if usr:
            usr.api_vk_key = access_token
            usr.save()
        else:
            Client.objects.create(user=request.user, api_vk_key=access_token)

    return render(request, 'users/auth_vk_complete.html', context)

def api_key_update_ok(request):
    usr = Client.objects.get(user=request.user)
    usr.api_vk_key = ''
    usr.save()
    return render(request, 'user_cabinet/api_key_update_complete.html', {} )


def auth_vk_key(request):
    return render(request, 'users/auth_vk_key.html')

randomizer/users/templates/users/access_denied.html
В доступе отказано.

randomizer/users/templates/users/auth_vk.html
{% extends 'base.html' %}
{% block title %}Добавление API-ключа{% endblock %}
{% block content %}
{% if not error %}
  <div class="col-md-8 p-3 ">
    <div class="card">
      <div class="card-header alert alert-success">
        Успешно
      </div>
      <div class="card-body">
        <p>
          Вы успешно добавили ключ ВК в систему!<br>
          Теперь можно <a href="{% url 'generator:new_raffle' %}">проводить конкурсы</a> ;)<br>
        </p>
      </div>
    </div>
  </div>
{% else %}
<div class="col-md-8 p-3 ">
    <div class="card">
      <div class="card-header alert alert-danger">
        Неуспешно
      </div>
      <div class="card-body">
        <p>
          Сервер Вконтакте передал информацию об ошибке:<br>
          <p class="alert-secondary rounded" style="padding: 5px;"><var>{{ error_description }}</var></p>
          Возможно, вы не дали приложению доступ к просмотру групп.<br>
          Это необходимо для его корректной работы.<br>
          Пожалуйста, попробуйте <a href="https://oauth.vk.com/authorize?client_id=51526721&display=page&redirect_uri=https://goraffle.ru/auth/auth_vk/&scope=groups+offline&response_type=token&v=5.131&state=123456" target="_blank">получить ключ снова</a>.
        </p>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %} 

randomizer/users/templates/users/auth_vk_complete.html
{% extends 'base.html' %}
{% block title %}Добавление API-ключа{% endblock %}
{% block content %}
{% if not error %}
  <div class="col-md-8 p-3 ">
    <div class="card">
      <div class="card-header alert alert-success">
        Успешно
      </div>
      <div class="card-body">
        <p>
          Вы успешно добавили ключ ВК в систему!<br>
          Теперь можно <a href="{% url 'generator:new_raffle' %}">проводить конкурсы</a> ;)<br>
        </p>
      </div>
    </div>
  </div>
{% else %}
<div class="col-md-8 p-3 ">
    <div class="card">
      <div class="card-header alert alert-danger">
        Неуспешно
      </div>
      <div class="card-body">
        <p>
          Сервер Вконтакте передал информацию об ошибке:<br>
          <p class="alert-secondary rounded" style="padding: 5px;"><var>{{ error_description }}</var></p>
          Возможно, вы не дали приложению доступ к просмотру групп.<br>
          Это необходимо для его корректной работы.<br>
          Пожалуйста, попробуйте <a href="https://oauth.vk.com/authorize?client_id=51527760&display=page&redirect_uri=https://goraffle.ru/auth/auth_vk_get_params/&scope=groups+offline&response_type=token&v=5.131&state=123456" target="_blank">получить ключ снова</a>.
        </p>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %} 

randomizer/users/templates/users/auth_vk_key.html
{% extends 'base.html' %}
{% block title %}Добавление API-ключа{% endblock %}
{% block content %}

<p style="padding: 5px; margin: 5px;">
    Обрабатываем ответ Вконтакте ...
</p>
<p>
<script>
var msg = document.location.href
msg = '?' + msg.substring(45)
document.writeln(msg)
window.location.replace("https://goraffle.ru/auth/auth_vk_complete/" + msg);
</script>
</p>
{% endblock %} 

randomizer/users/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="col-md-8 p-3">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
{% endblock %} 

randomizer/users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Ваш помощник в проведении конкурсов{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-7 p-4">
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}


    <h4>Войти на сайт</h4>
    <div class="form-group">
      <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
          aria-required="false" {% endif %}>
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
            <span class="required text-danger">*</span>
            {% endif %}
          </label>
          <div>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">

          Войти
        </button>
      </form>
      <div class="dropdown-divider"></div>

      <a class="dropdown-item" href="{% url 'users:signup' %}">Впервые здесь? Зарегистрируйтесь</a>
      <a class="dropdown-item" href="{% url 'users:password_reset_form' %}">Забыли пароль?</a>
    </div>
  </div>
  {% endblock %}

randomizer/users/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
{% load user_filters %}
        <div class="row justify-content-left">
          <div class="col-md-7 p-4">
            <div class="card">
              <div class="card-header">
                Всё получилось
              </div>
              <div class="card-body"> 
                <p>Пароль успешно изменён</p>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

randomizer/users/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменить пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-left">
  <div class="col-md-7 p-4">
    <div class="card">
      <div class="card-header">
        Изменить пароль
      </div>
      <div class="card-body">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
            aria-required="false" {% endif %}>
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
          <button type="submit" class="btn btn-outline-primary">
            Изменить пароль
          </button>
      </div>
      </form>
    </div> <!-- card body -->
  </div> <!-- card -->
</div> <!-- col -->
</div> <!-- row -->
{% endblock %}

randomizer/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Изменить пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Восстановление пароля завершено
      </div>
      <div class="card-body">
        <p>Ваш пароль был сохранен. Используйте его для входа</p>
        <a href="../users/login.html">войти</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

randomizer/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
  {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
  {{ error|escape }}
</div>
{% endfor %}
{% endif %}
<form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %} aria-required="false"
    {% endif %}>
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
      <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
      {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
      {% endif %}
    </div>
  </div>
  {% endfor %}

  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-7 p-4">
      <div class="card">
        <div class="card-header">Ошибка</div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  {% endif %}

  {% endblock %}

randomizer/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Изменить пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-7 p-4">
    <div class="card">
      <div class="card-header">
        Отправлено письмо
      </div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

randomizer/users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Изменить пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-7 p-4">
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}


    <h4>Сбросить пароль</h4>
    <div class="form-group">
      <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
          aria-required="false" {% endif %}>
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
            <span class="required text-danger">*</span>
            {% endif %}
          </label>
          <div>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">

          Выслать письмо
        </button>
      </form>
    </div>
  </div>
  {% endblock %}

randomizer/users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-7 p-4">
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}


    <h4>Зарегистририроваться</h4>
    <div class="form-group">
      <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
          aria-required="false" {% endif %}>
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
            <span class="required text-danger">*</span>
            {% endif %}
            {% if field.name == 'email'%}
            <span class="required text-danger">*</span>
            {% endif %}
          </label>
          <div>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">

          Зарегистрироваться
        </button>
      </form>
      <div class="dropdown-divider"></div>

      <a class="dropdown-item" href="{% url 'users:login' %}">Уже зарегистрированы? Войдите</a>
    </div>
  </div>
  {% endblock %}