randomizer/generator/urls.py
from django.urls import path
from generator.views import *

app_name = 'generator'
urlpatterns = [
    path('', index, name='index'),
    path('raffles/<slug:slug>/', raffle_page, name='raffle_page'),
    path('my_raffles/', my_raffles, name='my_raffles'),
    path('new_raffle/', VkForm.as_view(), name='new_raffle'),
    path('thankyou/', thankyou, name='thankyou'),

]

randomizer/randomizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('generator.urls')),
    path('lk/', include('user_cabinet.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

randomizer/users/urls.py
from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                    )
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('access_denied/', access_denied, name='access_denied'),
    path('auth_vk_key/', auth_vk_key, name='auth_vk_key'),
    path('auth_vk_complete/', auth_vk_complete, name='auth_vk_complete'),
        
]

randomizer/generator/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


User = get_user_model()


class Raffle(models.Model):

    # Fields
    title = models.CharField(max_length=200, verbose_name='Введите заголовок:')
    slug = models.SlugField(unique=True, null=False, verbose_name='Введите слаг-адрес:')
    description = models.CharField(max_length=500, verbose_name='Какой будет приз?')
    link = models.URLField(verbose_name='Введите ссылку на пост Вконтакте:')
    is_subscribers = models.BooleanField(verbose_name='Учитывать только участников группы')
    qty_winners = models.PositiveIntegerField(verbose_name='Введите желаемое количество победителей:')
    winner = models.TextField(verbose_name='Победитель')
    winner_url = models.TextField(verbose_name='Ссылка на страницу победителя')
    winner_photo = models.TextField(verbose_name='Ссылка на фото победителя')
    winner_first_name = models.TextField(verbose_name='Имя победителя')
    winner_last_name = models.TextField(verbose_name='Фамилия победителя')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания конкурса')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения конкурса')
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='raffles',
        verbose_name=''
    )

    class Meta:
        ordering = ('-time_create',)

    def __str__(self):
        return self.title


class Client(models.Model):

    # Fields
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, verbose_name='Пользователь')
    api_vk_key = models.CharField(null=True, max_length=500, verbose_name='Ключ VK API')
    paid_up_to = models.DateField(null=True, verbose_name='Оплачено до')
    display_name = models.CharField(max_length=120, null=True, verbose_name='Введите новый псевдоним:')

    def __str__(self):
        return self.user.get_username()

randomizer/generator/forms.py
from django import forms

from generator.models import Raffle


class VkForm(forms.ModelForm):
    class Meta:
        # Raffle form
        model = Raffle
        fields = ('description', 'link',
                  'qty_winners', 'is_subscribers')

randomizer/generator/views.py
from django.shortcuts import render, redirect
from generator.models import Raffle
from django.views.generic.edit import CreateView
from generator.forms import VkForm
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime as dt
from generator.functions import get_winner
from random import randint
from django.core.paginator import Paginator

def authorized_only(func):
    def check_user(request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(request, *args, **kwargs)
        return redirect('/auth/login/')
    return check_user

def lk(request):
    return render(request, 'generator/lk.html')


@authorized_only
def index(request):
    raf = Raffle.objects.filter(creator=request.user).count()
    raffles = Raffle.objects.filter(creator=request.user)[:5]
    context = {
        'raffles': raffles,
        'len_raf': raf,
    }

    return render(request, 'generator/index.html', context)


@authorized_only
def raffle_page(request, slug):
    raffles = Raffle.objects.filter(slug=slug)
    context = {
        'raffles': raffles,
    }

    return render(request, 'generator/raffle_page.html', context)


@authorized_only
def my_raffles(request):
    raffles = Raffle.objects.filter(creator=request.user)
    
    paginator = Paginator(raffles, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'paginator': paginator
    }

    return render(request, 'generator/my_raffles.html', context)


@authorized_only
def thankyou(request):
    delay = randint(9000, 11000)
    raffles = Raffle.objects.filter(creator=request.user)[:1]
    context = {
        'raffles': raffles,
        'delay': delay,
    }
    return render(request, 'generator/thx.html', context)


class VkForm(LoginRequiredMixin, CreateView):
    form_class = VkForm
    model = Raffle
    template_name = 'generator/rfl.html'
    success_url = '/thankyou/'

    def form_invalid(self, form):    
        print(123)
        return None

    def form_valid(self, form):


        form.instance.creator = self.request.user
        user = form.instance.creator
        # pk = form.instance.pk

        # api_key_vk
        api_vk_key = self.request.user.client.api_vk_key

        # title
        title = form.instance.title
        now = dt.now()
        now_text = now.strftime("%d-%m-%Y %H:%M:%S")
        print(now)
        if not title:
            form.instance.title = f'Конкурс #{user} {now_text}'

        # description
        description = form.instance.description
        if not description:
            form.instance.description = f'Конкурс #{user} {now_text}'

        # slug
        slug = form.instance.slug
        now_slug = now.strftime("%d%m%Y%H%M%S%s")
        if not slug:
            form.instance.slug = f'{user}_{now_slug}'

        # winner
        winner = form.instance.winner
        if not winner:
            link = form.instance.link
            qty_winners = form.instance.qty_winners
            description = form.instance.description
            winners = get_winner(
                                link,
                                api_vk_key,
                                qty_winners,
                                form.instance.is_subscribers
            )
            if isinstance(winners, int):
                
                is_subscribers = form.instance.is_subscribers
                
                # если вернулся код о некорректности ссылки
                # обнуляем строку, чтоб вернуть начальную форму
                # но без строки
                if winners == -2:
                    link = ''

                context = {
                    'error_code': winners,
                    'r_description': description,
                    'r_link': link,
                    'r_qty_winners': qty_winners,
                    'r_is_subscribers': is_subscribers,
                
                }
                return render(self.request, 'generator/raffle_error.html', context)
            try:
                length_winners = len(winners)
                for i in range(length_winners):
                    form.instance.winner += f'{winners[i][0]}#'
                    form.instance.winner_url += f'{winners[i][1]}#'
                    form.instance.winner_photo += f'{winners[i][2]}#'
                    form.instance.winner_first_name += f'{winners[i][3]}#'
                    form.instance.winner_last_name += f'{winners[i][4]}#'
            except:
                form.instance.winner_first_name = 'netu'

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(VkForm, self).get_context_data(**kwargs)
        context['r_error_code'] = self.request.GET.get('r_error_code', '')
        context['r_title'] = self.request.GET.get('r_title', '')
        context['r_description'] = self.request.GET.get('r_description', '')
        context['r_link'] = self.request.GET.get('r_link')
        context['r_qty_winners'] = self.request.GET.get('r_qty_winners', '')
        context['r_is_subscribers'] = self.request.GET.get('r_is_subscribers', '')


        return context
    

randomizer/generator/templates/generator/index.html
{% extends 'base.html' %}
{% block title %}Лучшие конкурсы тут{% endblock %}
{% block content %}
{% load user_filters %}
<div class="dropdown-menu p-4 text-muted" style="max-width: 200px;">
  <p>
    Пример текста, который свободно перемещается в выпадающем меню.
  </p>
  <p class="mb-0">
    И это еще один пример текста.
  </p>
</div>
<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break">
    <legend>
      <h4>Дашборд</h4>

      <table class="table table-borderless">

        <td>
          {% if user.client.display_name %}
            Пользователь: {{ user.client.display_name }}
          {% elif user.first_name %}
            Пользователь: {{ user.first_name }}
          {% else %}
            Пользователь: {{ user.get_username }}
          {% endif %}
        </td>
        <td>
          Конкурсов проведено: {{ len_raf }}
        </td>


      </table>
    </legend>
  </div>
  <br>
  <div class="card col-md-12 p-4 text-break">
    <fieldset>
      <legend>
        <h4>Мои последние конкурсы</h4>
      </legend>
      {% if len_raf %}
      <table class="table table-hover ">
        <caption>Показана краткая информация для последних конкурсов. Для получения полной
          информации перейдите на страницу с подробностями</caption>
        <thead>
          <tr class="nohower">
            <td><b>Приз</b></td>
            <td><b>Ccылка на пост</b></td>
            <td><b>Победитель<b></td>
            <td><b>Дата проведения<b></td>
          </tr>
        </thead>
        <tbody>
          {% for raffle in raffles%}
          <tr onclick="window.location.href='{% url 'generator:raffle_page' raffle.slug %}'; return false">
            <td>{{ raffle.description|truncatechars:45 }}</td>
            <td>{{ raffle.link }}</td>
            <td>
              {% for win in raffle.winner_url|str_to_list|slice:":1" %}
                {{ win }}
              {% if not forloop.last %}<br>{% endif %}
              {% endfor %}
              {% if raffle.winner_url|str_to_list_length != 1 %} [...] {% endif %}
            </td>
            <td>{{ raffle.time_create|date:"d E Y"}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'generator:my_raffles' %}"><button type="submit"
          class="btn btn-outline-primary">Все мои конкурсы</button></a>

    </fieldset>
    {% else %}
    Конкурсы не проводились. Пока что
    <br>
    <br>
    <a class="nav-link" href="{% url 'generator:new_raffle' %}"><button type="submit"
        class="btn btn-outline-primary">Провести первый конкурс</button></a>
    {% endif %}
  </div>
</div>
{% endblock %}
{% block footer %}
  <div class="p-2 bg-light">
    <div class="card col-md-12 p-4 text-break ">Сложности с использованием ресурса? <a href="https://t.me/twsomt" target="_blank">Свяжитесь с нами.</a></div>
  </div>
{% endblock %}

randomizer/generator/templates/generator/my_raffles.html
{% extends 'base.html' %}
{% block title %}Мои конкурсы{% endblock %}
{% block content %}
{% load user_filters %}
<div class="p-2 bg-light ">
    <br>
    <div class="card col-md-12 p-4 text-break">
        <legend>
            <h4>Все мои конкурсы</h4>
        </legend>

        {% for raffle in page_obj%}
        <div onclick="window.location.href='{% url 'generator:raffle_page' raffle.slug %}';"
            class="card col-md-7 p-4 text-break box">
            <table class="table">
                <tr>
                    <td>Приз</td>
                    <td>{{raffle.description}}</td>
                </tr>
                <tr>
                    <td>Ссылка на пост</td>
                    <td><a href="{{raffle.link}}" target="_blank">{{raffle.link }}</a></td>
                </tr>
                
                <tr>
                    <td>Дата и время создания</td>
                    <td>{{raffle.time_create|date:"d E Y H:i:s"}}</td>
                </tr>
            </table>
        </div>

        <br>
        {% endfor %}


        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if not page_obj.number == 1 %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="page-item active"><a class="page-link disabled" href="">{{ p }}</a></li>
                    {% elif p >= page_obj.number|add:-5 and p <= page_obj.number|add:5 %} 
                        <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if not page_obj.number == paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ paginator.num_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<style>
    .box:hover {
        /* border-color: rgb(13, 110, 253); */
        background-color: rgb(247, 247, 247);
        /* border-color: #0d6efd; */
        transition: 0.0s;

    }
</style>
{% endblock %}

randomizer/generator/templates/generator/raffle_error.html
{% extends "base.html" %}
{% block title %}Новый конкурс{% endblock %}
{% block content %}
{% load user_filters %}
Обрабатываем данные

<script>
    window.location.replace("{% url 'generator:new_raffle' %}?r_title={{ r_title }}&r_description={{ r_description }}&r_link={{ r_link }}&r_qty_winners={{ r_qty_winners }}&r_is_subscribers={{ r_is_subscribers }}&r_error_code={{ error_code }}");
</script>

{% endblock %}

randomizer/generator/templates/generator/raffle_page.html
{% extends 'base.html' %}
{% block title %}Подробнее о конкурсе{% endblock %}
{% block content %}
{% load user_filters %}
<div class="p-2 bg-light">
    <br>
    <div class="card col-md-12 p-4 text-break">
    <legend>
        <h4>Подробнее о конкурсе</h4>
    </legend>
    {% if user.get_username|to_str == raffles.0.creator|to_str %}

        {% for raffle in raffles%}
        
            <table class="table">
                <tr>
                    <td>Приз</td>
                    <td>{{raffle.description}}</td>
                </tr>
                <tr>
                    <td>Ссылка на пост</td>
                    <td><a href="{{raffle.link}}" target="_blank">{{raffle.link}}</a></td>
                </tr>
                <tr>
                    <td>
                        {% if raffle.winner_url|str_to_list|length == 1 %}
                        Победитель
                        {% else %}
                        Победители
                        {% endif %}
                    </td>
                    <td>
                        {% for win in raffle.winner_url|str_to_list %}
                        <a href="{{ win }}" target="_blank">{{ win }}</a>
                        {% if not forloop.last %}<br>{% endif %}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td>Дата и время создания</td>
                    <td>{{raffle.time_create|date:"d E Y H:i:s"}}</td>
                </tr>
                <tr>
                    <td>Автор конкурса</td>
                    {% if user.client.display_name %}
                        <td>{{ user.client.display_name }}</td>
                    {% elif user.first_name and user.last_name %}
                        <td>{{ user.get_full_name }}</td>
                    {% else %}
                        <td>{{ user.get_username }}</td>
                    {% endif %}
                </tr>
            </table>
            <div>
                <a href="{% url 'generator:my_raffles' %}" class="align-end"><button type="submit"
                        class="btn btn-outline-primary">Все мои конкурсы</button></a>
                {% define raffle.title|code as r_title %}
                {% define raffle.description|code as r_description %}
                {% define raffle.link|code as r_link %}
                {% define raffle.qty_winners|code as r_qty_winners %}
                {% define raffle.is_subscribers|code as r_is_subscribers %}
                <a href="{% url 'generator:new_raffle' %}?r_title={{ r_title }}&r_description={{ r_description }}&r_link={{ r_link }}&r_qty_winners={{ r_qty_winners }}&r_is_subscribers={{ r_is_subscribers }}" class='float-end repeat_button'><button type="submit"
                    class="btn btn-outline-primary">Повторить конкурс</button></a>
                
            </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="instrcution border alert-danger rounded" style="margin: 10px; padding: 10px;">
        Конкурс не существует или недостаточно прав для его просмотра.
    </div>
    {% endif %}
{% endblock %}

randomizer/generator/templates/generator/rfl.html
{% extends "base.html" %}
{% block title %}Новый конкурс{% endblock %}
{% block content %}
{% load user_filters %}


{% if user.client.api_vk_key %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
  {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
  {{ error|escape }}
</div>
{% endfor %}
{% endif %}

<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break">
    <legend>
      <h4>Новый конкурс</h4>
    </legend>
    {% if r_error_code %}
    <div class="border alert-danger rounded" style="margin: 10px; padding: 10px;">
      Указанная Вами ссылка не валидна. Это может быть по следующим причинам:
      <ul>
        <li>Пост не относится к группе или паблику Вконтакте</li>
        <li>Пост не существует</li>
        <li>На посте отсутствует активность</li>
        <li>У вас нет доступа к этому посту</li>
      </ul>
      Мы обнулили ссылку на пост, и сохранили остальные данные.
    </div>
    {% endif %}
    <div class="instrcution border alert-danger rounded" style="margin: 10px; padding: 10px;">
      Вы ошибочно заполнили форму конкурса. Давайте всё исправим!
      <ul>
        <li>Вcе поля со звёздочкой должны быть заполнены</li>
        <li>В поле со ссылкой укажите ссылку на пост из паблика Вконтакте (скопируйте из адресной строки)</li>
        <li>В поле количество победителей укажите положительное число</li>
      </ul>

    </div>


    <form method="post" class='needs-validation' action="{% url 'generator:new_raffle' %}" novalidate>
      {% csrf_token %}

      {% for field in form %}

      <div class="mb-2">
        {% if field.name == 'is_subscribers'%}
        {% if r_is_subscribers == 'True' %}
        {{ field|addchecked:'checked'}}
        {% else %}
        {{ field }}
        {% endif %}
        {{ field.label }}
        {% else %}
        <label class="form-label" for="{{ field.id_for_label }}">

          {{ field.label }}
          {% if field.field.required %}
          <span class="required text-danger">*</span>
          {% endif %}
        </label>

        {% if field.name == 'link' %}
        {% if r_link %}
        {{ field|addvalue:r_link }}
        {% else %}
        {{ field|addplaceholder:'https://vk.com/wall-7568821_681441'}}
        {% endif %}

        {% elif field.name == 'title' %}
        {% if r_title %}
        {{ field|addvalue:r_title }}
        {% else %}
        {{ field|addplaceholder:'Конкурс для группы с лучшими подписчиками'}}
        {% endif %}

        {% elif field.name == 'description'%}
        {% if r_description %}
        {{ field|addvalue:r_description }}
        {% else %}
        {{ field|addplaceholder:'5кг оливье'}}
        {% endif %}

        {% elif field.name == 'qty_winners'%}
        {% if r_qty_winners %}
        {{ field|addvalue:r_qty_winners}}
        {% else %}
        {{ field|addplaceholder:'1'}}
        {% endif %}

        {% elif field.name == 'is_subscribers'%}
        {% if r_is_subscribers %}
        {{ field|addclass:'checked'}}
        {% endif %}

        {% else %}
        {{ field|addclass:'form-control' }}
        {% endif %}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
        {% endif %}
        {% endif %}
      </div>
      {% endfor %}





      <a href="#"><button type="submit" class="btn btn-outline-primary block1" id="ActivateLoader">Определить
          победителя</button></a>
      <a href="">
        <button" class="btn block2" id="ActivateLoader">
          <div class="spinner-border text-primary" role="status">
          </div>
          </button>
      </a>

    </form>
  </div>


  {% else %}
  <div class="p-2 bg-light">
    <br>
    <div class="card col-md-12 p-4 text-break">
      <legend>
        <h4>Новый конкурс</h4>
      </legend>
      <div class="border alert-danger rounded" style="margin: 10px; padding: 10px;">
        Отсутствует корректный API - ключ
        <br>
        <br>
        <a href="https://oauth.vk.com/authorize?client_id=51527760&display=page&redirect_uri=https://goraffle.ru/auth/auth_vk_key/&scope=groups+offline&response_type=token&v=5.131&state=123456"
          target="_blank">Получить ключ</a>
      </div>
    </div>
  </div>
  {% endif %}


  <script>
    (function () {
      'animate if form is valid'
      $('.block2').hide();
      $('.instrcution').hide();
      var forms = document.querySelectorAll('.needs-validation')
      Array.prototype.slice.call(forms)
        .forEach(function (form) {
          form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
              event.preventDefault()
              event.stopPropagation()
              $('.instrcution').fadeIn();
            } else {
              $('.block2').hide();
              setTimeout(() => {
                $('.block1').hide();
                $('.instrcution').hide();
                $('.block2').fadeIn();
              }, {{ 200 }})
        }
        }, false)
    })
    }) ()

  </script>
  {% endblock %}

randomizer/generator/templates/generator/thx.html
{% extends 'base.html' %}
{% block title %}Результат конкурса{% endblock %}
{% block content %}
{% load user_filters %}
{% load static %}

<div class="p-2 bg-light">
    <br>
    <div class="card col-md-12 p-4 text-break">
        <legend>
            {% if raffles.0.qty_winners == 1 %}
                <div class="process_title">Определяем победитeля...</h4></div>
            {% else %}
                <div class="process_title">Определяем победитeлей...</h4></div>
            {% endif %}
            <div class="complete_title">Конкурс завершен успешно!</h4></div>
        </legend>
        {% for raffle in raffles%}
        <table class="table align-middle">
            <tr>
                <td><span class="align-middle">Приз</span></td>
                <td><span class="align-middle">{{ raffle.description }}</span></td>
            </tr>
            <tr>
                <td><span class="align-middle">Ссылка на пост</td>
                <td><span class="align-middle"><a href="{{ raffle.link }}" target="_blank">{{raffle.link}}</a></span>
                </td>
            </tr>
            <tr>
                <td><span class="align-middle">
                        Победители
                    </span>
                </td>
                <td class="block1">
                    <div class="spinner-border text-primary" role="status">
                    </div>
                </td>
                <td class="block2">
                    <span class="align-middle">
                        {% define raffle.winner_url|str_to_list as winner_url %}
                        {% define raffle.winner_photo|str_to_list as winner_photo %}
                        {% define raffle.winner_first_name|str_to_list as winner_first_name %}
                        {% define raffle.winner_last_name|str_to_list as winner_last_name %}
                        <div class="shows">
                        {% for i in raffle.winner|str_to_list|length|make_range %}
                        
                            <div>
                                <img src="{{ winner_photo|index:i }}" alt="Победитель" class="rounded" style="margin-left: -5px;">
                                <a href="{{ winner_url|index:i }}" target="_blank"> {{ winner_first_name|index:i }} {{ winner_last_name|index:i }}</a>
                            </div>
                        {% endfor %}
                        </div>
                    </span>
                </td>
            </tr>
            <tr>
                <td><span class="align-middle">Дата и время создания</span></td>
                <td><span class="align-middle">{{ raffle.time_create|date:"d E Y H:i:s" }}</span></td>
            </tr>
            {% if not raffle.time_create|date:"d E Y H i s" == raffle.time_update|date:"d E Y H i s" %}
            <tr>
                <td><span class="align-middle">Дата и время изменения</span></td>
                <td><span class="align-middle">{{ raffle.time_update|date:"d E Y H:i:s" }}</span></td>
            </tr>
            {% endif %}
            <tr>
                <td><span class="align-middle">Автор конкурса</span></td>
                {% if user.client.display_name %}
                    <td><span class="align-middle">{{ user.client.display_name }}</span></td>
                {% elif user.first_name and user.last_name %}
                    <td><span class="align-middle">{{ user.get_full_name }}</span></td>
                {% else %}
                    <td><span class="align-middle">{{ user.get_username }}</span></td>
                {% endif %}
            </tr>
        </table>



        <div>
            <a href="{% url 'generator:my_raffles' %}" class="align-end"><button type="submit"
                    class="btn btn-outline-primary">Все мои конкурсы</button></a>
            {% define raffle.title|code as r_title %}
            {% define raffle.description|code as r_description %}
            {% define raffle.link|code as r_link %}
            {% define raffle.qty_winners|code as r_qty_winners %}
            {% define raffle.is_subscribers|code as r_is_subscribers %}
            <a href="{% url 'generator:new_raffle' %}?r_title={{ r_title }}&r_description={{ r_description }}&r_link={{ r_link }}&r_qty_winners={{ r_qty_winners }}&r_is_subscribers={{ r_is_subscribers }}" class='float-end repeat_button'><button type="submit"
                class="btn btn-outline-primary">Повторить конкурс</button></a>
            
        </div>
    </div>
</div>

{% endfor %}
<script>
    jQuery(document).ready(function ($) {   
        $('.repeat_button').hide();
        $('.block2').hide();
        $('.complete_title').hide();
        setTimeout(() => {
            $('.block1').hide();
            $('.block2').fadeIn();
            $('.shows div:eq(0)').fadeIn(1000, function(){
            $(this).next().fadeIn(1000, arguments.callee);
            });
        }, {{ delay }})
        setTimeout(() => {
            $('.process_title').hide();
            $('.complete_title').fadeIn();
            $('.repeat_button').fadeIn();
        }, {{ delay }} + ({{ raffles.0.qty_winners }} * 1000) + 50)
        
    })
</script>

<style>
    .list {
        margin: 5px;
        opacity: 0;
        animation: fade 1s linear forwards;
    }

    @keyframes fade {
        0% {
            opacity: 0;
        }

        100% {
            opacity: 1;
        }
    }
</style>

<style type="text/css">
.shows {
	overflow: hidden;
}
.shows div {
	display: none;
	margin: 5px;
}



</style>
<!-- <script>
    $('.shows div:eq(0)').fadeIn(2000, function(){
        $(this).next().fadeIn(1000, arguments.callee);
    });
</script> -->

{% endblock %}