randomizer/randomizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('generator.urls')),
    path('lk/', include('user_cabinet.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

randomizer/user_cabinet/urls.py
from django.urls import path
from user_cabinet.views import *

app_name = 'user_cabinet'
urlpatterns = [
    path('', index_lk, name='index_lk'),
    path('display_name_update/', DisplayNameUpdate.as_view(), name='display_name_update'),
    path('display_name_update_ok', display_name_update_ok, name='display_name_update_ok'),
    path('api_key_update', api_key_update, name='api_key_update'),
    path('api_key_update_ok', api_key_update_ok, name='api_key_update_ok'),
]

randomizer/users/urls.py
from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                    )
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('access_denied/', access_denied, name='access_denied'),
    path('auth_vk_key/', auth_vk_key, name='auth_vk_key'),
    path('auth_vk_complete/', auth_vk_complete, name='auth_vk_complete'),
        
]

randomizer/user_cabinet/models.py
from django.db import models

# Create your models here.

randomizer/user_cabinet/forms.py
from django import forms

from generator.models import Client


class DisplayNameUpdate(forms.ModelForm):
    class Meta:
        # Client form
        model = Client
        fields = ('display_name',)

randomizer/user_cabinet/views.py
from django.shortcuts import render
from generator.views import authorized_only
from generator.models import Client
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from user_cabinet.forms import DisplayNameUpdate


@authorized_only
def index_lk(request):
    return render(request, 'user_cabinet/index_lk.html', {})


@authorized_only
def display_name_update(request):
    return render(request, 'user_cabinet/display_name_update_form.html', {} )


@authorized_only
def display_name_update_ok(request):
    display_name = request.POST.get('display_name')
    try:
        usr = Client.objects.get(user=request.user)
    except:
        usr = False

    if usr:
        usr.display_name = display_name
        usr.save()
    else:
        Client.objects.create(user=request.user, display_name=display_name)

    if display_name:
        text = 'Псевдоним успешно изменен на'
        name = display_name
    else:
        text = 'Псевдоним успешно сброшен'
        name = ''

    context = {
        'text':text,
        'name':name,
    }
    return render(request, 'user_cabinet/display_name_update_complete.html', context )


def api_key_update(request):
    return render(request, 'user_cabinet/api_key_update_form.html', {} )


def api_key_update_ok(request):
    usr = Client.objects.get(user=request.user)
    usr.api_vk_key = ''
    usr.save()
    return render(request, 'user_cabinet/api_key_update_complete.html', {} )

class DisplayNameUpdate(LoginRequiredMixin, CreateView):
    form_class = DisplayNameUpdate
    model = Client
    template_name = 'user_cabinet/display_name_update_form.html'
    success_url = '/display_name_update_ok/'

randomizer/user_cabinet/templates/user_cabinet/api_key_update_complete.html
{% extends "base.html" %}
{% block title %}Изменить отображаемое имя пользователя{% endblock %}
{% block content %}
<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break ">


    <legend class="align-end">
      <h4><span class="text-muted">Личный кабинет:</span> изменить / удалить VK API ключ</h4>
    </legend>
    <div>
      API ключ ВК был успешно удален из системы
    </div>
    
    <div class='float-end'>
      <a href="{% url 'user_cabinet:index_lk' %}"><button class="btn btn-outline-secondary mt-3">Назад</button>
  </div>
  </div>
  
</div>
{% endblock %}

randomizer/user_cabinet/templates/user_cabinet/api_key_update_form.html
{% extends "base.html" %}
{% block title %}Изменить отображаемое имя пользователя{% endblock %}
{% load user_filters %}
{% block content %}

<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break ">
    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}

    <legend class="align-end">
      <h4><span class="text-muted">Личный кабинет:</span> изменить / удалить VK API ключ</h4>
    </legend>
    <div class="mt-2">
        <div>
          <a href="https://oauth.vk.com/authorize?client_id=51527760&display=page&redirect_uri=https://goraffle.ru/auth/auth_vk_key/&scope=groups+offline&response_type=token&v=5.131&state=123456"
      target="_blank">
            <button type="submit" class="btn btn-outline-primary mt-3">
              Добавить новый ключ в систему
            </button>
          </a>
          <p class="mt-1">
            <span class="text-muted">
              Вы будете переадресованы на страницу Вконтакте, где необходимо авторизовать наше приложение.
            </span>
          </p>
        </div>
      </form>
      {% if user.client.api_vk_key %}
        <div>
          <a href="{% url 'user_cabinet:api_key_update_ok' %}">
            <button class="btn btn-outline-danger mt-2">
              Удалить текущий ключ
            </button>
          </a>
          <p class="mt-1">
            <span class="text-muted">
              Вы можете в любой момент удалить свой ВК-ключ из системы, однако он необходим для проведения конкурсов.
            </span><br>
            <span class="text-muted">
              При проведении конкурса (если ключ будет отсутствовать) вы получите уведомление о необходимости его добавить.
            </span>
          </p>
        </div>
      {% endif %}
        
    </div>
    <div class='float-end'>
      <a href="{% url 'user_cabinet:index_lk' %}"><button class="btn btn-outline-secondary mt-2">Назад</button>
  </div>
  </div>
  
</div>
  {% endblock %}

randomizer/user_cabinet/templates/user_cabinet/display_name_update_complete.html
{% extends "base.html" %}
{% block title %}Изменить отображаемое имя пользователя{% endblock %}
{% block content %}
<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break ">


    <legend class="align-end">
      <h4><span class="text-muted">Личный кабинет:</span> изменить / удалить отображаемый псевдоним</h4>
    </legend>
    <div>
      {{ text }} <span class="text-muted">{{ name }}</span>
    </div>
    
    <div class='float-end'>
      <a href="{% url 'user_cabinet:index_lk' %}"><button class="btn btn-outline-secondary mt-3">Назад</button>
  </div>
  </div>
  
</div>
{% endblock %}

randomizer/user_cabinet/templates/user_cabinet/display_name_update_form.html
{% extends "base.html" %}
{% block title %}Изменить отображаемое имя пользователя{% endblock %}
{% load user_filters %}
{% block content %}

<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break ">
    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}

    <legend class="align-end">
      <h4><span class="text-muted">Личный кабинет:</span> изменить / удалить отображаемый псевдоним</h4>
    </legend>
    <div>
      Текущей псевдоним:
      {% if user.client.display_name %}
        <span class="text-muted">{{ user.client.display_name }}</span>
      {% else %}
        <span class="text-muted">Отсутствует</span>
      {% endif %}
    </div>
    <div class="mt-2">
      <form method="post" action="{% url 'user_cabinet:display_name_update_ok' %}">
        {% csrf_token %}
        {% for field in form %}
          {{ field.label }}
          {{ field|addclass:'form-control' }}
        {% endfor %}
        <div>
          <button type="submit" class="btn btn-outline-primary mt-3">Применить изменения</button>
        </div>
      </form>
      {% if user.client.display_name %}
        <div>
          <a href="{% url 'user_cabinet:display_name_update_ok' %}">
            <button class="btn btn-outline-danger mt-3">
              Нажмите для сброса псевдонима
            </button>
          </a>
        </div>
      {% endif %}
        
    </div>
    <div class='float-end'>
      <a href="{% url 'user_cabinet:index_lk' %}"><button class="btn btn-outline-secondary mt-3">Назад</button>
  </div>
  </div>
  
</div>
  {% endblock %}

randomizer/user_cabinet/templates/user_cabinet/index_lk.html
{% extends 'base.html' %}
{% block title %}Личный кабинет{% endblock %}
{% block content %}
{% load user_filters %}
<div class="p-2 bg-light">
  <br>
  <div class="card col-md-12 p-4 text-break ">


    <legend class="align-end">
      <h4>Личный кабинет</h4>
    </legend>
    <div>

      <div class="container">
        <div class="row align-items-left">

          <div class="col">
            <div class="card mb-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Данные аккаунта</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  {% if user.first_name and user.last_name %}
                    <li>Имя и фамилия: {{ user.get_full_name }}</li>
                  {% endif %}
                  <li>Логин: {{ user.get_username }}</li>
                  <li>Email: twsomt@ya.ru</li>
                  <li>Дата регистрации: 25.12.2022</li>
                  {% if user.client.display_name %}
                  <li>Отображаемое имя: {{ user.client.display_name }}</li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="card mb-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Настройки</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  <!-- <li><a href="">Изменить конкурс-таймаут</a></li> -->
                  <li><a href="{% url 'user_cabinet:display_name_update' %}">Изменить / удалить</a> псевдоним</li>
                  <li><a href="{% url 'user_cabinet:api_key_update' %}">Изменить / удалить</a> API-ключ</li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Оплата и тарифы</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  {% comment %}
                    <li>Оплачено конкурсов: 999 999 999</li>
                  {% endcomment %}
                  <li>Текущий тариф: Безграничный</li>
                  <li>Действителен до: 31.12.2023</li>
                  <!-- <li><a href="">Изменить тариф</a></li> -->
                  <!-- <li><a href="">Оплатить</a></li> -->
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='float-end'>
      <button type="submit" class="btn btn-outline-secondary">Выход из аккаунта</button></div>
  </div>
</div>

{% endblock %}